### PR TITLE
build: add SOURCE_DATE_EPOCH=0

### PR DESCRIPTION
**Pull request by PaperMountainStudio**

### CODE REVIEW

**Comment by mitchweaver** [comment]
And we're sure this doesn't create any conflicts? Have you rebuilt at least @core and a few programs with it?

**Comment by PaperMountainStudio** [comment]
I did try a few programs. But not core. Will try.

**Comment by PaperMountainStudio** [comment]
`@core` works

**Comment by mitchweaver** [comment]
Setting this before make sets it in `ENV` for the make command.

Are we sure we don't want to force define it as a variable instead?
ie `make SOURCE_DATE_EPOCH=0 ...` ?

**Comment by PaperMountainStudio** [comment]
I don't know. But it is an environment variable for gcc. If we define it like `make SOURCE_DATE_EPOCH=0` it will override if it is defined inside Makefile, right?

**Comment by mitchweaver** [comment]
Yes, it will. However if it's a `gcc` variable its reading, then perhaps we do need it in the env. I'm not sure if `gcc` will pick it up if its just a variable defined in the makefile, not the ENV.

Using it in ENV is probably better for now.

Honestly this is something only useful for reproducible builds which we won't come to til far, far down along the line. As it is now I don't see much point of it being merged.

**Pull request closed without merging**
